<Project Sdk="Microsoft.NET.Sdk">

	<!-- These define the critical project details. Such as the net version, C# language version, null enable and do not generate assembly info (we need a custom one) -->
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<LangVersion>Latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<DebugType>none</DebugType>
		<Version>2.0.0</Version>
		<Title>Item Rarities</Title>
		<Authors>Deadman</Authors>
		<Description>Item Rarities is a modification that gives each item within The Long Dark a sense of exclusivity.</Description>
		<Copyright>Copyright (c) 2023-2024 Deadman</Copyright>
		<PackageProjectUrl>https://tldmods.com/?q=itemrarities</PackageProjectUrl>
		<PackageLicenseUrl>https://github.com/Deaadman/ItemRarities/blob/release/LICENSE</PackageLicenseUrl>
		<RepositoryUrl>https://github.com/Deaadman/ItemRarities</RepositoryUrl>
		<PackageTags>thelongdark, tld, mods</PackageTags>
		<PackageReleaseNotes>https://github.com/Deaadman/ItemRarities/releases</PackageReleaseNotes>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<PropertyGroup>
		<!-- This should point to wherever your games primary EXE is -->
		<TheLongDarkPath>C:\Program Files (x86)\Steam\steamapps\common\TheLongDark</TheLongDarkPath>
		<ReleaseFolderPath>D:\The Long Dark\Projects\Maintained\ItemRarities\Release</ReleaseFolderPath>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
	  <DocumentationFile>bin\Debug\ItemRarities.xml</DocumentationFile>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
	  <DocumentationFile>bin\Release\ItemRarities.xml</DocumentationFile>
	</PropertyGroup>
	
	<!-- List of used references -->
	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="STBlade.Modding.TLD.Il2CppAssemblies.Windows" Version="2.35.0" />
		<PackageReference Include="STBlade.Modding.TLD.LocalizationUtilities" Version="2.0.0" />
		<PackageReference Include="STBlade.Modding.TLD.ModSettings" Version="1.9.0" />
	</ItemGroup>

	<!-- Most commonly used using's. Add to this so you dont need to define them in the cs files -->
	<ItemGroup>
		<Using Include="System.Reflection" />
		<Using Include="System.Diagnostics.CodeAnalysis" />
		<Using Include="Il2Cpp" />
		<Using Include="HarmonyLib" />
		<Using Include="MelonLoader" />
		<Using Include="UnityEngine" />
	</ItemGroup>
	<ItemGroup>
	  <None Remove="Resources\Localization.json" />
	  <EmbeddedResource Include="Resources\Localization.json" />
	  <None Remove="Resources\ItemRarities.json" />
	  <EmbeddedResource Include="Resources\ItemRarities.json" />
	</ItemGroup>

	<!-- This is a build event. It will copy your dll to the currently defined TheLongDarkPath's Mods folder -->
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<!-- This copies the mods files to the games mod dir -->
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(TheLongDarkPath)/Mods" />
		<!-- This copies the mods files to a designated release folder. Speeds up finding the dll after a build -->
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ReleaseFolderPath)" />
	</Target>
</Project>
